---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

## Assignment 4 - Understanding and Predicting Property Maintenance Fines

This assignment is based on a data challenge from the Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)). 

The Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)) and the Michigan Student Symposium for Interdisciplinary Statistical Sciences ([MSSISS](https://sites.lsa.umich.edu/mssiss/)) have partnered with the City of Detroit to help solve one of the most pressing problems facing Detroit - blight. [Blight violations](http://www.detroitmi.gov/How-Do-I/Report/Blight-Complaint-FAQs) are issued by the city to individuals who allow their properties to remain in a deteriorated condition. Every year, the city of Detroit issues millions of dollars in fines to residents and every year, many of these fines remain unpaid. Enforcing unpaid blight fines is a costly and tedious process, so the city wants to know: how can we increase blight ticket compliance?

The first step in answering this question is understanding when and why a resident might fail to comply with a blight ticket. This is where predictive modeling comes in. For this assignment, your task is to predict whether a given blight ticket will be paid on time.

All data for this assignment has been provided to us through the [Detroit Open Data Portal](https://data.detroitmi.gov/). **Only the data already included in your Coursera directory can be used for training the model for this assignment.** Nonetheless, we encourage you to look into data from other Detroit datasets to help inform feature creation and model selection. We recommend taking a look at the following related datasets:

* [Building Permits](https://data.detroitmi.gov/Property-Parcels/Building-Permits/xw2a-a7tf)
* [Trades Permits](https://data.detroitmi.gov/Property-Parcels/Trades-Permits/635b-dsgv)
* [Improve Detroit: Submitted Issues](https://data.detroitmi.gov/Government/Improve-Detroit-Submitted-Issues/fwz3-w3yn)
* [DPD: Citizen Complaints](https://data.detroitmi.gov/Public-Safety/DPD-Citizen-Complaints-2016/kahe-efs3)
* [Parcel Map](https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwf)

___

We provide you with two data files for use in training and validating your models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

<br>

**File descriptions** (Use only this data for training your model!)

    readonly/train.csv - the training set (all tickets issued 2004-2011)
    readonly/test.csv - the test set (all tickets issued 2012-2016)
    readonly/addresses.csv & readonly/latlons.csv - mapping from ticket id to addresses, and from addresses to lat/lon coordinates. 
     Note: misspelled addresses may be incorrectly geolocated.

<br>

**Data fields**

train.csv & test.csv

    ticket_id - unique identifier for tickets
    agency_name - Agency that issued the ticket
    inspector_name - Name of inspector that issued the ticket
    violator_name - Name of the person/organization that the ticket was issued to
    violation_street_number, violation_street_name, violation_zip_code - Address where the violation occurred
    mailing_address_str_number, mailing_address_str_name, city, state, zip_code, non_us_str_code, country - Mailing address of the violator
    ticket_issued_date - Date and time the ticket was issued
    hearing_date - Date and time the violator's hearing was scheduled
    violation_code, violation_description - Type of violation
    disposition - Judgment and judgement type
    fine_amount - Violation fine amount, excluding fees
    admin_fee - $20 fee assigned to responsible judgments
state_fee - $10 fee assigned to responsible judgments
    late_fee - 10% fee assigned to responsible judgments
    discount_amount - discount applied, if any
    clean_up_cost - DPW clean-up or graffiti removal cost
    judgment_amount - Sum of all fines and fees
    grafitti_status - Flag for graffiti violations
    
train.csv only

    payment_amount - Amount paid, if any
    payment_date - Date payment was made, if it was received
    payment_status - Current payment status as of Feb 1 2017
    balance_due - Fines and fees still owed
    collection_status - Flag for payments in collections
    compliance [target variable for prediction] 
     Null = Not responsible
     0 = Responsible, non-compliant
     1 = Responsible, compliant
    compliance_detail - More information on why each ticket was marked compliant or non-compliant


___

## Evaluation

Your predictions will be given as the probability that the corresponding blight ticket will be paid on time.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC). 

Your grade will be based on the AUC score computed for your classifier. A model which with an AUROC of 0.7 passes this assignment, over 0.75 will recieve full points.
___

For this assignment, create a function that trains a model to predict blight ticket compliance in Detroit using `readonly/train.csv`. Using this model, return a series of length 61001 with the data being the probability that each corresponding ticket from `readonly/test.csv` will be paid, and the index being the ticket_id.

Example:

    ticket_id
       284932    0.531842
       285362    0.401958
       285361    0.105928
       285338    0.018572
                 ...
       376499    0.208567
       376500    0.818759
       369851    0.018528
       Name: compliance, dtype: float32
       
### Hints

* Make sure your code is working before submitting it to the autograder.

* Print out your result to see whether there is anything weird (e.g., all probabilities are the same).

* Generally the total runtime should be less than 10 mins. You should NOT use Neural Network related classifiers (e.g., MLPClassifier) in this question. 

* Try to avoid global variables. If you have other functions besides blight_model, you should move those functions inside the scope of blight_model.

* Refer to the pinned threads in Week 4's discussion forum when there is something you could not figure it out.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score

def blight_model():
    df=pd.read_csv('train.csv', encoding='mac_roman')
    df.index=df['ticket_id']
    df=df[df['compliance'].notnull()]    
    X=df[['fine_amount', 'admin_fee', 'state_fee', 'late_fee']]    
    y=df.compliance
    X_train,X_test,y_train,y_test=(train_test_split(X,y))    
        
    model = RandomForestRegressor(random_state=0)
    param_grid = {'n_estimators':[5,6,7,8,9,10], 'max_depth':[4,5,10,12]}
    grid_search = GridSearchCV(model, param_grid, scoring="roc_auc")
    grid_result = grid_search.fit(X_train, y_train)
    print("Best: %f using %s" % (grid_search.best_score_, grid_search.best_params_))
    return grid_result.predict(X_test)
    

svm=blight_model()

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3254: DtypeWarning: Columns (11,12,31) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [66]:
X_test

           fine_amount  admin_fee  state_fee  late_fee
ticket_id
33984            250.0       20.0       10.0       0.0
211387           250.0       20.0       10.0      25.0
185050            50.0       20.0       10.0       0.0
181869           250.0       20.0       10.0      25.0
248312           250.0       20.0       10.0      25.0
...                ...        ...        ...       ...
20183            250.0       20.0       10.0       0.0
29293            100.0       20.0       10.0      10.0
103486           250.0       20.0       10.0       0.0
250822            50.0       20.0       10.0       5.0
163672           100.0       20.0       10.0      10.0

[39970 rows x 4 columns]

In [65]:
svm

           compliance
ticket_id
137230       0.037421
213644       0.062014
47176        0.308476
67601        0.062014
152230       0.037421
...               ...
59731        0.309187
81912        0.037421
201022       0.011542
113868       0.037421
158964       0.037421

[39970 rows x 1 columns]

In [48]:
df=pd.read_csv('train.csv', encoding='mac_roman')
df.index=df['ticket_id']
df=df[df['compliance'].notnull()]
X=df[['fine_amount', 'admin_fee', 'state_fee', 'late_fee']]    
y=df.compliance    
X_train,X_test,y_train,y_test=(train_test_split(X,y))

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (11,12,31) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [40]:
print(svm.score(X_test,y_test))

0.9284963722792094

In [41]:
y_score=svm.predict(X_test)

In [42]:
X_test.shape

(39970, 4)

In [43]:
y_score.shape

(39970,)

In [44]:
y_test.shape

(39970,)

In [45]:
fpr, tpr, _ = roc_curve(y_test, y_score)
roc_auc = auc(fpr, tpr)
print(roc_auc)

0.5106568052774796

In [4]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc

svm

SVC(probability=True)

In [38]:
y=df[['compliance']]
y=y.fillna(-1)

In [39]:
y

           compliance
ticket_id
22056             0.0
27586             1.0
22062            -1.0
22084            -1.0
22093            -1.0
...               ...
325555           -1.0
325557           -1.0
325562           -1.0
325559           -1.0
325561           -1.0

[250306 rows x 1 columns]

In [34]:
feature=df[['fine_amount', 'admin_fee', 'state_fee', 'late_fee']]
feature.head()

           fine_amount  admin_fee  state_fee  late_fee
ticket_id
22056            250.0       20.0       10.0      25.0
27586            750.0       20.0       10.0      75.0
22062            250.0        0.0        0.0       0.0
22084            250.0        0.0        0.0       0.0
22093            250.0        0.0        0.0       0.0

In [60]:
df['disposition']

ticket_id
22056           Responsible by Default
27586     Responsible by Determination
22046           Responsible by Default
18738           Responsible by Default
18735           Responsible by Default
                      ...
285106          Responsible by Default
284650          Responsible by Default
285125          Responsible by Default
284881    Responsible by Determination
284333          Responsible by Default
Name: disposition, Length: 159880, dtype: object

In [23]:
df.index=df['ticket_id']
df.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
ticket_id,,,,,,,,,,,,,,,,,,,,,
22056,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
27586,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
22062,22062,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","SANDERS, DERRON",1449.0,LONGFELLOW,NaN,23658.0,P.O. BOX,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
22084,22084,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","MOROSI, MIKE",1441.0,LONGFELLOW,NaN,5.0,ST. CLAIR,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
22093,22093,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","NATHANIEL, NEAL",2449.0,CHURCHILL,NaN,7449.0,CHURCHILL,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN

In [20]:
df[df['compliance'].notnull()].count()

ticket_id                     159880
agency_name                   159880
inspector_name                159880
violator_name                 159854
violation_street_number       159880
violation_street_name         159880
violation_zip_code                 0
mailing_address_str_number    157322
mailing_address_str_name      159877
city                          159880
state                         159796
zip_code                      159879
non_us_str_code                    3
country                       159880
ticket_issued_date            159880
hearing_date                  159653
violation_code                159880
violation_description         159880
disposition                   159880
fine_amount                   159880
admin_fee                     159880
state_fee                     159880
late_fee                      159880
discount_amount               159880
clean_up_cost                 159880
judgment_amount               159880
payment_amount                159880
balance_due                   159880
payment_date                   39611
payment_status                159880
collection_status              36897
grafitti_status                    0
compliance_detail             159880
compliance                    159880
dtype: int64

In [ ]:
blight_model()

In [12]:
df=df[df['compliance'].notnull()]

In [13]:
df

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
ticket_id,,,,,,,,,,,,,,,,,,,,,
22056,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
27586,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
22046,22046,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","KASIMU, UKWELI",6478.0,NORTHFIELD,NaN,2755.0,E. 17TH,LOG BEACH,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
18738,18738,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Deerwood Development Group Inc, Deer",8027.0,BRENTWOOD,NaN,476.0,Garfield,Clinton,...,0.0,855.0,0.0,855.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
18735,18735,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Rafee Auto Services L.L.C., RAF",8228.0,MT ELLIOTT,NaN,8228.0,Mt. Elliott,Detroit,...,0.0,140.0,0.0,140.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285106,285106,Department of Public Works,"Zizi, Josue","LUNDY, ANTONIO R",20009.0,NORTHLAWN,NaN,18715.0,MARLOWE,DETROIT,...,0.0,250.0,0.0,250.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
284650,284650,Department of Public Works,"Lusk, Gertrina","HARDAWAY, WILLIE",15725.0,STEEL,NaN,NaN,P.O. BOX 27125,DETROIT,...,0.0,1130.0,0.0,1130.0,NaN,NO PAYMENT APPLIED,IN COLLECTION,NaN,non-compliant by no payment,0.0
285125,285125,Department of Public Works,"Bell, Maydell","CHRISTIAN CHURCH, BRIGHT STAR",7152.0,CHICAGO,NaN,7152.0,W. CHICAGO,DETROIT,...,0.0,580.0,0.0,580.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
284881,284881,Department of Public Works,"Johnson, Lois","INC., HANTZ GROUP",17403.0,MT ELLIOTT,NaN,1743.0,MT ELLIOTT,DETROIT,...,0.0,230.0,230.0,0.0,2012-02-07 00:00:00,PAID IN FULL,NaN,NaN,compliant by on-time payment,1.0
284333,284333,Department of Public Works,"Granberry, Aisha B","AMERICAN INTERNATIONAL ASS. LL, .",15634.0,NOVARA,NaN,72.0,MANGROVE,CHICO,...,0.0,250.0,0.0,250.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0